name: file-deleter
description: Deletes a list of files

inputs:
  file-list:
    description: The list of file to be deleted
    required: true

runs:
  using: "composite"
  steps:
    - name: Delete files
      id: delete_files
      shell: bash
      run: |-
        echo "${{ inputs.file-list}}"
        FILES=$(echo "${{ inputs.file-list }}" | tr '\n' ' ')
        for file in ${FILES}; do
          [[ -f "$file" ]] && rm -v "$file" || true
        done